// Client-side access to the OSHB morphology data in `public/data/morphhb/`,
// generated by `scripts/build-morphhb.mjs`. Mirrors greek-tools' `morphgnt.ts`.
//
// The parse-code formatter is `src/lib/morph-parse.ts`, not here — turning
// `HC/Vqw3ms` into "Conjunction + Qal wayyiqtol 3ms" is a display concern that
// Daily Verse (issue #76) and the Reader (issue #77) share, and it carries its
// own tables, its own tests and its own inventory of what the corpus attests.

// ─── Types ────────────────────────────────────────────────────────────────────

export interface HebrewWord {
  /**
   * The word as the Westminster Leningrad Codex writes it, pointed and accented,
   * with `/` marking the boundaries between morphemes. Use `displayText` to
   * render it and `morphemes` to take it apart — never render this raw.
   */
  text: string;
  /** Key into `lemmas.json`: an augmented Strong's number (`1121a`) or an
   * inseparable prefix's letter code (`l`, `b`, `c`). */
  lemma: string;
  /** Coarse part of speech of the head morpheme — `Nc`, `Np`, `Vq`, `R`, `C`. */
  pos: string;
  /** The full OSHB morph string, including its `H`/`A` language marker. */
  parsing: string;
  /** Maqqef, paseq or sof pasuq that follows this word. */
  after?: string;
  /** `text` is the ketiv — the consonantal form as written, without pointing. */
  ketiv?: true;
  /** The pointed qere: what is read where it differs from what is written. */
  qere?: string;
  /** Read but not written — a qere with no ketiv (`qere wela ketiv`). */
  qereOnly?: true;
}

export type HebrewVerse = HebrewWord[];
/** chapter string key → verse string key → words */
export type HebrewBook = Record<string, Record<string, HebrewVerse>>;

/** Which of the Hebrew Bible's three divisions a book belongs to. */
export type TanakhSection = 'torah' | 'neviim' | 'ketuvim';

export interface HebrewBookMeta {
  /** Paratext/USFM code — `GEN`, `1SA`, `PSA`. */
  code: string;
  name: string;
  /** The book's Hebrew name, pointed. */
  hebrew: string;
  section: TanakhSection;
  chapters: number;
  words: number;
}

/**
 * One `lemmas.json` entry.
 *
 * `count` is always present — it is a fact about the corpus. Everything else
 * comes from the OSHB Hebrew Lexicon and is absent for the handful of lemmas it
 * cannot resolve, so treat all of it as optional.
 */
export interface LemmaEntry {
  /** Occurrences in the WLC, counted per morpheme. */
  count: number;
  /** Pointed lexical form, cantillation stripped. */
  hebrew?: string;
  /** Transliteration as the lexicon gives it. */
  xlit?: string;
  /** Lexicon part of speech — `N`, `Np`, `V`, `A`, `R`, `C`. */
  pos?: string;
  /**
   * Lexical gender, from the corpus's own coding of the lemma's noun
   * occurrences. `fm` means attested both ways. Absent for words that never
   * occur as a common noun.
   */
  gender?: 'm' | 'f' | 'fm';
  /** Triliteral root, where the lexicon's etymology reaches one. */
  root?: string;
}

export type LemmaIndex = Record<string, LemmaEntry>;

// ─── Text helpers ─────────────────────────────────────────────────────────────

/**
 * The word as it should appear on screen.
 *
 * `HebrewWord.text` keeps OSHB's `/` morpheme boundaries because they are real
 * information — that וַיְהִי is וַ + יְהִי is a first-year skill, and throwing the
 * split away at build time would make it unrecoverable. Rendering them is still
 * wrong, so every display path goes through here.
 */
export function displayText(word: Pick<HebrewWord, 'text'>): string {
  return word.text.replace(/\//g, '');
}

/** The form a reader should show: the qere where there is one, else the text. */
export function readingText(word: HebrewWord): string {
  return word.qere ? word.qere.replace(/\//g, '') : displayText(word);
}

export interface Morpheme {
  /** The morpheme's letters, without boundary markers. */
  text: string;
  /** Its OSHB morph code — `C`, `Rd`, `Ncfsc`, `Sp3ms`. */
  morph: string;
}

/**
 * Split a word into its morphemes, each paired with its own morph code.
 *
 * OSHB's text segments and morph segments are 1:1 across all 305,516 words in
 * the corpus, which is what makes this a zip rather than an alignment problem.
 * A word whose two lists disagree — only ever a data anomaly — yields as many
 * pairs as the shorter list, rather than pairing letters with the wrong code.
 */
export function morphemes(word: Pick<HebrewWord, 'text' | 'parsing'>): Morpheme[] {
  const texts = word.text.split('/');
  const codes = word.parsing.replace(/^[HA]/, '').split('/');
  const count = Math.min(texts.length, codes.length);
  return Array.from({ length: count }, (_, i) => ({ text: texts[i], morph: codes[i] }));
}

/** True when the word comes from an Aramaic section — Daniel, Ezra, Jer 10:11. */
export function isAramaic(word: Pick<HebrewWord, 'parsing'>): boolean {
  return word.parsing.startsWith('A');
}

// Stripping diacritics lives in `src/lib/hebrew-input.ts` alongside `stripNikud`
// and `stripAllDiacritics`, which predate this module — a reader's "hide
// cantillation" toggle and lenient answer grading are the same operation, and a
// second set of Unicode ranges here would be a second set to get subtly wrong.
// `scripts/lib/oshb.mjs` keeps its own copy only because Node cannot import the
// TypeScript; `morphhb.test.ts` asserts the two agree.

// ─── Fetch + cache ────────────────────────────────────────────────────────────

const bookCache = new Map<string, HebrewBook>();
let booksCache: HebrewBookMeta[] | null = null;
let lemmaCache: LemmaIndex | null = null;

export async function fetchBook(code: string): Promise<HebrewBook> {
  const cached = bookCache.get(code);
  if (cached) return cached;
  const res = await fetch(`/data/morphhb/${code}.json`);
  if (!res.ok) throw new Error(`Failed to load ${code}: HTTP ${res.status}`);
  const data = (await res.json()) as HebrewBook;
  bookCache.set(code, data);
  return data;
}

export async function fetchBooks(): Promise<HebrewBookMeta[]> {
  if (booksCache) return booksCache;
  const res = await fetch('/data/morphhb/books.json');
  if (!res.ok) throw new Error(`Failed to load books index: HTTP ${res.status}`);
  booksCache = (await res.json()) as HebrewBookMeta[];
  return booksCache;
}

/**
 * The lemma index. Around 140 KB over the wire, so fetch it when a feature
 * actually needs a gloss or a frequency, not on page load.
 */
export async function fetchLemmas(): Promise<LemmaIndex> {
  if (lemmaCache) return lemmaCache;
  const res = await fetch('/data/morphhb/lemmas.json');
  if (!res.ok) throw new Error(`Failed to load lemma index: HTTP ${res.status}`);
  lemmaCache = (await res.json()) as LemmaIndex;
  return lemmaCache;
}

/** Drop every cached fetch. Exists for tests. */
export function clearMorphhbCache(): void {
  bookCache.clear();
  booksCache = null;
  lemmaCache = null;
}

// ─── Reading position ─────────────────────────────────────────────────────────

export const READER_HISTORY_KEY = 'hebrew-tools-reader-last';

export function saveLastPassage(ref: string): void {
  try {
    localStorage.setItem(READER_HISTORY_KEY, ref);
  } catch {
    /* ignore */
  }
}

export function loadLastPassage(): string | null {
  try {
    return localStorage.getItem(READER_HISTORY_KEY);
  } catch {
    return null;
  }
}
